[32m[0721 20:27:37 @logger.py:92][0m Argv: /usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py -f /root/.local/share/jupyter/runtime/kernel-df2f652a-6a36-4a45-bf7e-6da5e9b81f72.json
[32m[0721 20:27:37 @fs.py:101][0m [5m[31mWRN[0m Env var $TENSORPACK_DATASET not set, using /root/tensorpack_data for datasets.
[32m[0721 20:27:37 @fs.py:104][0m Created the directory /root/tensorpack_data.
[32m[0721 20:27:37 @mnist.py:21][0m Downloading to /root/tensorpack_data/mnist_data/train-images-idx3-ubyte.gz...
[32m[0721 20:27:37 @fs.py:64][0m [4m[5m[31mERR[0m Failed to download http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
